job:
    pattern:  /list/{offset}/{itemCount}
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:index", offset:0, itemCount:10 }
    requirements:
        offset: \d+
        itemCount: \d+
        _method: Get

job_search_redirect:
    pattern: /search
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:searchRedirect" }

job_search:
    pattern: /search/{query}/{offset}/{itemCount}
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:search", offset:0, itemCount:10 }
    requirements:
        offset: \d+
        itemCount: \d+
        _method: get

own_jobs:
    pattern: /user
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:own" }

job_show:
    pattern:  /{id}/show
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:show" }
    requirements:
        id: \d+

job_new:
    pattern:  /new
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:new" }

job_create:
    pattern:  /create
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:create" }
    requirements: { _method: post }

job_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:edit" }
    requirements:
        id: \d+

job_update:
    pattern:  /{id}/update
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:update" }
    requirements:
        _method: post|put
        id: \d+

job_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:delete" }
    requirements:
        _method: post|delete
        id: \d+

job_report:
    pattern: /{id}/report
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:report" }
    requirements:
        _method: get
        id: \d+

job_handle_report:
    pattern: /{id}/report
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:handleReport" }
    requirements:
        _method: post|put
        id: \d+

job_handle_rating:
    pattern: /{id}/rate
    defaults: { _controller: "AmsterdamPHPJobBundle:Job:handleRating" }
    requirements:
        _method: post|put
        id: \d+