jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        job_posting:
            pattern: ^/
            security: true
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: job

            logout:
                path: /logout
                target: job
            anonymous:    true

        admin:
            pattern: ^/admin
            security: true
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: overview
            logout:
                path: /logout
                target: job
            anonymous:    false

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/job/new, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/job/create, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/job/.*/edit$, roles: IS_AUTHENTICATED_FULLY}
        - { path: ^/job/update, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/job/delete, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
