parameters:
#    amsterdam_php_admin.example.class: AmsterdamPHP\AdminBundle\Example

services:
#    amsterdam_php_admin.example:
#        class: %amsterdam_php_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
