parameters:
#    amsterdam_php_job.example.class: AmsterdamPHP\JobBundle\Example

services:
#    amsterdam_php_job.example:
#        class: %amsterdam_php_job.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
