parameters:
#    amsterdam_php_job.example.class: AmsterdamPHP\JobBundle\Example

services:
    job_rating_update_listener:
        class: AmsterdamPHP\JobBundle\EventListener\JobRatingUpdater
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    sen_abuse_report_listener:
        class: AmsterdamPHP\JobBundle\EventListener\AbuseReportMailer
        arguments: [@templating, @mailer]
        tags:
            - { name: kernel.event_listener, event:send_abuse_report, method:onEvent }
