AmsterdamPHP\UserBundle\Entity\User:
    type: entity
    table: fos_user
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

        name:
            type: string
            size: 255

        linkedin:
            type: string
            size: 255
            nullable: true

        facebook:
            type: string
            size: 255
            nullable: true

        twitter:
            type: string
            size: 255
            nullable: true

        phone:
            type: string
            size: 15
            nullable: true

        company:
            type: string
            size: 255
            nullable: true




    lifecycleCallbacks: {  }
